# Generated by Django 5.2.1 on 2026-02-07 19:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("statements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("checking", "Checking"),
                            ("savings", "Savings"),
                            ("credit_card", "Credit Card"),
                            ("investment", "Investment"),
                            ("loan", "Loan"),
                            ("other", "Other"),
                        ],
                        default="checking",
                        max_length=20,
                    ),
                ),
                ("institution", models.CharField(blank=True, max_length=100)),
                ("last_four", models.CharField(blank=True, max_length=4)),
                ("color", models.CharField(default="#3B82F6", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Credit limit for credit cards",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Starting balance when account was added",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Account",
                "verbose_name_plural": "Financial Accounts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AccountBalanceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=12)),
                ("as_of_date", models.DateField()),
                (
                    "source",
                    models.CharField(
                        choices=[("statement", "Statement"), ("manual", "Manual Entry")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="accounts_financial.account",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="balance_snapshots",
                        to="statements.creditcardstatement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Balance Snapshot",
                "verbose_name_plural": "Balance Snapshots",
                "ordering": ["-as_of_date", "-created_at"],
            },
        ),
    ]
