# Generated by Django 5.2.1

from django.db import migrations


def migrate_statements_to_accounts(apps, schema_editor):
    """
    Create accounts from existing statements grouped by (user, bank_name).
    Link statements and their transactions to the created accounts.
    """
    CreditCardStatement = apps.get_model('statements', 'CreditCardStatement')
    Account = apps.get_model('accounts_financial', 'Account')
    Transaction = apps.get_model('transactions', 'Transaction')

    # Bank name mapping for display
    BANK_DISPLAY = {
        'amex': 'American Express',
        'chase': 'Chase',
        'wells_fargo': 'Wells Fargo',
        'boa': 'Bank of America',
        'other': 'Other',
    }

    # Group statements by user and bank
    processed_combos = set()

    for statement in CreditCardStatement.objects.filter(account__isnull=True):
        combo_key = (statement.user_id, statement.bank_name)

        if combo_key not in processed_combos:
            # Create or get account for this user/bank combo
            bank_display = BANK_DISPLAY.get(statement.bank_name, 'Unknown Bank')

            account, created = Account.objects.get_or_create(
                user_id=statement.user_id,
                institution=bank_display,
                account_type='credit_card',
                defaults={
                    'name': f"{bank_display} Credit Card",
                    'color': '#3B82F6',
                }
            )
            processed_combos.add(combo_key)

        else:
            # Get existing account
            bank_display = BANK_DISPLAY.get(statement.bank_name, 'Unknown Bank')
            account = Account.objects.get(
                user_id=statement.user_id,
                institution=bank_display,
                account_type='credit_card',
            )

        # Link statement to account
        statement.account = account
        statement.save()

        # Link all transactions from this statement to the account
        Transaction.objects.filter(statement=statement, account__isnull=True).update(
            account=account,
            transaction_type='purchase',  # Default type for imported transactions
        )


def reverse_migration(apps, schema_editor):
    """Reverse: unlink statements and transactions from accounts."""
    CreditCardStatement = apps.get_model('statements', 'CreditCardStatement')
    Transaction = apps.get_model('transactions', 'Transaction')

    # Unlink statements
    CreditCardStatement.objects.filter(account__isnull=False).update(account=None)

    # Unlink transactions
    Transaction.objects.filter(account__isnull=False).update(account=None)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_financial", "0001_initial"),
        ("statements", "0002_initial"),
        ("transactions", "0004_add_account_fields"),
    ]

    operations = [
        migrations.RunPython(migrate_statements_to_accounts, reverse_migration),
    ]
