# Generated by Django 5.2.1 on 2026-02-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="enable_conscious_spending",
            field=models.BooleanField(
                default=False, help_text="Enable Conscious Spending Plan tracking"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="enable_wants_needs",
            field=models.BooleanField(default=False, help_text="Enable Wants vs Needs tracking"),
        ),
        migrations.AddField(
            model_name="user",
            name="monthly_income",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monthly income for budget calculations",
                max_digits=12,
                null=True,
            ),
        ),
    ]
