# Generated by Django 5.2.1 on 2026-02-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_secondary_categorization"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="debt_payoff_strategy",
            field=models.CharField(
                choices=[
                    ("avalanche", "Avalanche (Highest Interest First)"),
                    ("snowball", "Snowball (Smallest Balance First)"),
                ],
                default="avalanche",
                help_text="Strategy for ordering debt payoff",
                max_length=10,
            ),
        ),
    ]
