# Generated by Django 6.0.1 on 2026-01-25 01:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("budgets", "0001_initial"),
        ("statements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("merchant", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("transaction_number", models.CharField(blank=True, max_length=32)),
                ("ai_category_suggestion", models.CharField(blank=True, max_length=100)),
                ("ai_confidence", models.FloatField(blank=True, null=True)),
                ("is_recurring", models.BooleanField(default=False)),
                ("is_flagged", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="budgets.budgetcategory",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="statements.creditcardstatement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(fields=["user", "date"], name="transaction_user_id_8af7f1_idx"),
                    models.Index(
                        fields=["user", "category"], name="transaction_user_id_cb8cb9_idx"
                    ),
                    models.Index(
                        fields=["user", "merchant"], name="transaction_user_id_75dd3a_idx"
                    ),
                ],
            },
        ),
    ]
