# Generated by Django 5.2.1 on 2026-02-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="user_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
