# Generated by Django 5.2.1 on 2026-02-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_transaction_user_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="csp_bucket_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fixed", "Fixed Costs (50-60%)"),
                    ("investments", "Investments (10%+)"),
                    ("savings", "Savings Goals (5-15%+)"),
                    ("guilt_free", "Guilt-Free Spending (20-35%)"),
                ],
                help_text="Override the category's default CSP bucket",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="spending_type_override",
            field=models.CharField(
                blank=True,
                choices=[("need", "Need"), ("want", "Want"), ("savings", "Savings")],
                help_text="Override the category's default spending type",
                max_length=10,
                null=True,
            ),
        ),
    ]
