# Generated by Django 5.2.1 on 2026-02-07 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_financial", "0001_initial"),
        ("budgets", "0004_populate_category_defaults"),
        ("statements", "0002_initial"),
        ("transactions", "0003_secondary_categorization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="accounts_financial.account",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("posted", "Posted"), ("cleared", "Cleared")],
                default="posted",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("purchase", "Purchase"),
                    ("payment", "Payment"),
                    ("transfer", "Transfer"),
                    ("refund", "Refund"),
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("fee", "Fee"),
                    ("interest", "Interest"),
                ],
                default="purchase",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transfer_pair",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_transfer",
                to="transactions.transaction",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["account", "date"], name="transaction_account_4f6194_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["account", "status"], name="transaction_account_c7d002_idx"),
        ),
    ]
