# Generated by Django 5.2.1 on 2026-02-07 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_financial", "0001_initial"),
        ("statements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcardstatement",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="statements",
                to="accounts_financial.account",
            ),
        ),
    ]
