# Generated by Django 5.2.1 on 2026-02-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetcategory",
            name="default_csp_bucket",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fixed", "Fixed Costs (50-60%)"),
                    ("investments", "Investments (10%+)"),
                    ("savings", "Savings Goals (5-15%+)"),
                    ("guilt_free", "Guilt-Free Spending (20-35%)"),
                ],
                help_text="Default Conscious Spending Plan bucket",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="budgetcategory",
            name="default_spending_type",
            field=models.CharField(
                blank=True,
                choices=[("need", "Need"), ("want", "Want"), ("savings", "Savings")],
                help_text="Default spending type for transactions in this category",
                max_length=10,
                null=True,
            ),
        ),
    ]
