# Generated by Django 5.2.1 on 2026-02-07 20:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_financial", "0002_migrate_existing_statements"),
        ("budgets", "0004_populate_category_defaults"),
        ("transactions", "0004_add_account_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budgetcategory",
            options={
                "ordering": ["section", "display_order", "name"],
                "verbose_name_plural": "Budget Categories",
            },
        ),
        migrations.AddField(
            model_name="budgetcategory",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Order for displaying within section"
            ),
        ),
        migrations.AddField(
            model_name="budgetcategory",
            name="due_day",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Day of month this bill is due (1-31)", null=True
            ),
        ),
        migrations.AddField(
            model_name="budgetcategory",
            name="is_recurring",
            field=models.BooleanField(default=False, help_text="For bills with regular due dates"),
        ),
        migrations.AddField(
            model_name="budgetcategory",
            name="section",
            field=models.CharField(
                choices=[("fixed", "Fixed Expenses"), ("variable", "Variable Expenses")],
                default="variable",
                help_text="Whether this is a fixed or variable expense",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "original_balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Balance when debt tracking started",
                        max_digits=12,
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2, help_text="Current remaining balance", max_digits=12
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2, help_text="Annual percentage rate (APR)", max_digits=5
                    ),
                ),
                (
                    "minimum_payment",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum monthly payment required",
                        max_digits=10,
                    ),
                ),
                (
                    "extra_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Additional monthly payment beyond minimum",
                        max_digits=10,
                    ),
                ),
                (
                    "target_payoff_date",
                    models.DateField(
                        blank=True, help_text="Goal date to pay off this debt", null=True
                    ),
                ),
                ("color", models.CharField(default="#EF4444", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_account",
                    models.OneToOneField(
                        blank=True,
                        help_text="Optional link to financial account",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_debt",
                        to="accounts_financial.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Debts",
                "ordering": ["-interest_rate", "current_balance"],
            },
        ),
        migrations.CreateModel(
            name="DebtPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateField()),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Remaining balance after this payment",
                        max_digits=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "debt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="budgets.debt",
                    ),
                ),
                (
                    "linked_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="debt_payments",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavingsGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("emergency", "Emergency Fund"),
                            ("retirement", "Retirement"),
                            ("investment", "Investment"),
                            ("vacation", "Vacation"),
                            ("car", "Car"),
                            ("house", "House Down Payment"),
                            ("wedding", "Wedding"),
                            ("education", "Education"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Target amount to save", max_digits=12
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Current amount saved", max_digits=12
                    ),
                ),
                (
                    "target_date",
                    models.DateField(blank=True, help_text="Target date to reach goal", null=True),
                ),
                (
                    "monthly_contribution",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Planned monthly contribution",
                        max_digits=10,
                    ),
                ),
                (
                    "is_retirement",
                    models.BooleanField(
                        default=False, help_text="Whether this is a retirement account (401k, IRA)"
                    ),
                ),
                (
                    "employer_match_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Employer 401k match percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("color", models.CharField(default="#10B981", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to financial account",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_goals",
                        to="accounts_financial.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Savings Goal",
                "verbose_name_plural": "Savings Goals",
                "ordering": ["goal_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="SavingsContribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("contribution_date", models.DateField()),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Goal balance after this contribution",
                        max_digits=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "linked_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="savings_contributions",
                        to="transactions.transaction",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="budgets.savingsgoal",
                    ),
                ),
            ],
            options={
                "ordering": ["-contribution_date", "-created_at"],
            },
        ),
    ]
