# Generated by Django 5.2.1 on 2026-02-07 09:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("budgets", "0002_initial"),
        ("transactions", "0002_transaction_user_confirmed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("category_name", models.CharField(max_length=100)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ai", "AI Prediction"),
                            ("user", "User Correction"),
                            ("user_initial", "User Initial Selection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ai_confidence", models.FloatField(blank=True, null=True)),
                ("ai_model_version", models.CharField(blank=True, max_length=50)),
                ("transaction_description", models.CharField(max_length=255)),
                ("transaction_merchant", models.CharField(blank=True, max_length=255)),
                ("transaction_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="budgets.budgetcategory",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_assignments",
                        to="transactions.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "category_name"], name="categorizat_user_id_ef1c49_idx"
                    ),
                    models.Index(
                        fields=["transaction_description"], name="categorizat_transac_9e176d_idx"
                    ),
                ],
            },
        ),
    ]
